version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  animal-detector:
    lang: python3-http-debian
    handler: ./animal-detector
    image: keidikei/animal-detector:latest
